# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jessie Jo Fielding
email: jessiejofielding@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Jessie Fielding. I'm a Software Development Engineer at Seeq, and a
  Princeton University Class of 2021 graduate. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thejessiejo.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jessiejofielding

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site Author
author:
  name             : "Jessie"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "I'm not very good at writing bios."
  location         : "USA"
  # email            : "jessiejofielding@gmail.com"
  links:
    - label: "email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jessiejofielding@gmail.com"
    - label: "website"
      icon: "fas fa-fw fa-link"
      url: "https://thejessiejo.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jessiejofielding"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jessica-jo-fielding/"

search: true
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true